// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:bd003b29-ec3e-469f-99d7-de40da6a291e",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_A6MbgTVET",
    "aws_user_pools_web_client_id": "sfpt2d09pqm89dhetf4uv5674",
    "oauth": {},
    "aws_user_files_s3_bucket": "galeriatest-prueba",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
